### ISSUE TITLE
Method is auto even when we set an IP

### ISSUE THREAD

**Issue by itcultus** [alcamie101/ansible-nmcli#8]
I have created a bond interface with the nmcli module. 
The code is: 

```yaml
- name: Configure Network Team/Bond
  nmcli: 
    autoconnect: "{{ team.autoconnect | default ('yes') }}"
    conn_name: "{{ team.name }}"
    type: "{{ team.type | default('team') }}"
    mode: "{{ team.mode | default(omit) }}"
    state: "{{ team.state | default('present') }}"
    ip4: "{{ team.ip4 }}"
  loop: "{{ team_conf }}"
```

However, the connection has the method to auto: 

```bash
nmcli connection show Mng | grep method
ipv4.method:                            auto
```
